indent-width = 2
line-length = 100

[lint]
select = ["E", "F", "B", "UP", "RUF", "I"]
extend-select = ["PL"]
ignore = [
  "RUF001", "RUF002", "RUF003", "F405", "F403",
  "PLR0912", "PLR0915", "PLR0913", "PLR0911",
  "B008", "PLW2901", "RUF012", "PLC2401", "PLR2004",
  "PLW1509",
]

[lint.isort]
lines-after-imports = 2
